language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer self-update
  - composer install

script:
  - composer run cs
  - ./vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
